apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    batch.kubernetes.io/job-tracking: ""
  creationTimestamp: "2022-05-05T17:12:29Z"
  generation: 1
  labels:
    controller-uid: 3e553907-8c47-49f0-8fac-627a73a55eff
    job-name: hello-job1
  name: hello-job1
  namespace: default
  resourceVersion: "6036"
  uid: 3e553907-8c47-49f0-8fac-627a73a55eff
spec:
  backoffLimit: 6
  completionMode: NonIndexed
  completions: 1
  parallelism: 1
  selector:
    matchLabels:
      controller-uid: 3e553907-8c47-49f0-8fac-627a73a55eff
  suspend: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        controller-uid: 3e553907-8c47-49f0-8fac-627a73a55eff
        job-name: hello-job1
    spec:
      containers:
      - command:
        - echo
        - Hello
        image: busybox
        imagePullPolicy: Always
        name: hello-job1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
