---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: podsel
spec:
  containers:
    - name: podsel
      image: busybox:latest
      args:
        - sleep
        - "3600"
  nodeSelector:
    kind: special
