---
apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
    - image: redis
      name: secret-env-pod-container
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: creds
              key: username
              optional: false
                
